import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, join, dirname } from "node:path";
import { validateManifest, type Manifest } from "@fedkit/runtime";

export interface HostConfig {
  remotes: Array<{ name: string; manifest: string }>;
  /** Where to write fetched declarations. Default ".fedkit/types". */
  typesDir?: string;
}

export interface TypesSyncOptions {
  cwd?: string;
  /** Host config path. Default "fed.host.json". */
  config?: string;
}

/**
 * Fetch each remote's exposed `.d.ts` files and generate a declaration that augments
 * `@fedkit/runtime`'s `RemoteModules`, so `loadRemote("checkout/CartWidget")` is typed.
 *
 * Add the generated `typesDir` to your tsconfig `include` (or reference the file).
 */
export async function typesSyncCommand(
  opts: TypesSyncOptions = {},
): Promise<{ written: string[]; declarationPath: string; declaration: string }> {
  const cwd = opts.cwd ?? process.cwd();
  const configPath = resolve(cwd, opts.config ?? "fed.host.json");

  let host: HostConfig;
  try {
    host = JSON.parse(await readFile(configPath, "utf8")) as HostConfig;
  } catch {
    throw new Error(`No host config at ${configPath}. Create fed.host.json with { "remotes": [...] }.`);
  }
  if (!Array.isArray(host.remotes)) {
    throw new Error(`fed.host.json: "remotes" must be an array of { name, manifest }.`);
  }

  const typesDir = resolve(cwd, host.typesDir ?? ".fedkit/types");
  await mkdir(typesDir, { recursive: true });

  const written: string[] = [];
  const importLines: string[] = [];
  const entryLines: string[] = [];
  let idx = 0;

  for (const remote of host.remotes) {
    const { manifest, base } = await loadManifest(remote.manifest, cwd);
    for (const [key, decl] of Object.entries(manifest.exposes)) {
      if (typeof decl.types !== "string") continue;
      const keyBase = key.replace(/^\.\//, "");
      const text = await loadText(decl.types, base);

      const outDir = join(typesDir, remote.name);
      await mkdir(outDir, { recursive: true });
      const outPath = join(outDir, `${keyBase}.d.ts`);
      await writeFile(outPath, text, "utf8");
      written.push(outPath);

      const ident = `R${idx++}`;
      importLines.push(`import type ${ident} from ${JSON.stringify(`./${remote.name}/${keyBase}`)};`);
      entryLines.push(`    ${JSON.stringify(`${remote.name}/${keyBase}`)}: ${ident};`);
    }
  }

  const declaration =
    "// AUTO-GENERATED by `fedkit types sync`. Do not edit.\n" +
    (importLines.length ? importLines.join("\n") + "\n" : "") +
    'declare module "@fedkit/runtime" {\n' +
    "  interface RemoteModules {\n" +
    (entryLines.length ? entryLines.join("\n") + "\n" : "") +
    "  }\n}\nexport {};\n";

  const declarationPath = join(typesDir, "fedkit-remotes.d.ts");
  await writeFile(declarationPath, declaration, "utf8");

  return { written, declarationPath, declaration };
}

function isHttp(s: string): boolean {
  return s.startsWith("http://") || s.startsWith("https://");
}

async function loadManifest(ref: string, cwd: string): Promise<{ manifest: Manifest; base: string }> {
  if (isHttp(ref)) {
    const res = await fetch(ref);
    if (!res.ok) throw new Error(`Failed to fetch manifest ${ref}: HTTP ${res.status}`);
    return { manifest: validateManifest(await res.json(), ref), base: res.url || ref };
  }
  const path = resolve(cwd, ref);
  return { manifest: validateManifest(JSON.parse(await readFile(path, "utf8")), path), base: path };
}

async function loadText(typesRef: string, base: string): Promise<string> {
  if (isHttp(base)) {
    const url = new URL(typesRef, base).toString();
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to fetch types ${url}: HTTP ${res.status}`);
    return res.text();
  }
  return readFile(resolve(dirname(base), typesRef), "utf8");
}
